<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Asset URL
    |--------------------------------------------------------------------------
    |
    | This value is used to prefix relative asset URLs generated by Vite
    | typically for images or fonts. you may setit to null to let Laravel
    | figure out the asset URL automatically.
    |
    */

    'asset_url' => null,

    /*
    |--------------------------------------------------------------------------
    | Vite Entrypoints
    |--------------------------------------------------------------------------
    |
    | Here you may specify the entrypoints for your application. These are
    | the files that should be processed by Vite and include your CSS,
    | JavaScript, or other assets. Paths should be relative to the
    | resources directory and should not include a leading slash.
    |
    */

    'entrypoints' => [
        'resources/css/app.css',
        'resources/js/app.js',
    ],

    /*
    |--------------------------------------------------------------------------
    | Vite Hot File Location
    |--------------------------------------------------------------------------
    |
    | During development, Vite will place a "hot" file to indicate thatit is
    | running in hot-reload mode. This location is used by Laravel to detect
    | that mode and not use the built files.
    |
    */

    'hot_file' => storage_path('app/vite.hot'),

    /*
    |--------------------------------------------------------------------------
    | Build Directory
    |--------------------------------------------------------------------------
    |
    | This is the directory that Vite will build your assets into. It should
    | be relative to the public path and is used to locate your assets.
    |
    */

    'build_directory' => 'build',

    /*
    |--------------------------------------------------------------------------
    | Mainfest File
    |--------------------------------------------------------------------------
    |
    | This is the name of the mainfest file that Vite will generate when it
    | builds your assets. It is used by Laravel to locate the build files.
    |
    */

    'mainfest' => 'mainfest.json',

];